/*
 * This source file was generated by the Gradle 'init' task
 */
package com.fabio;

import com.fabio.client.ExchangeRateClientImpl;
import com.fabio.model.CurrenciesMenuOptionsEnum;
import com.fabio.service.ExchangeRateService;

import java.util.Scanner;

public class App {
    private final static Scanner scanner = new Scanner(System.in);

    public double getCalculatedExchangePrice(double currencyValue, String fromCurrency, String toCurrency) {
        ExchangeRateService exchangeRateService = new ExchangeRateService(new ExchangeRateClientImpl());

        return exchangeRateService.getCalculatedExchangeValue(currencyValue,fromCurrency, toCurrency);
    }

    public static void main(String[] args) {
        int currencyMenuLength = CurrenciesMenuOptionsEnum.values().length;

        while(true) {
            System.out.println("·····················································································");
            System.out.println("Convertor de Moedas by Fabio");

            for (CurrenciesMenuOptionsEnum menu : CurrenciesMenuOptionsEnum.values()) {
                int optionNumber = (menu.ordinal() + 1);
                if (menu.getFromCurrencySymbol() != null){
                    System.out.print(optionNumber + ") ");
                    System.out.print(menu.getFromCurrencySymbol() + " ");
                    System.out.print(menu.getFromCurrencyDesc());
                    System.out.print("  >>>>>>  ");
                    System.out.print(menu.getToCurrencySymbol() + " ");
                    System.out.println( menu.getToCurrencyDesc());
                    continue;
                }
                System.out.println(optionNumber + ") Sair");
            }

            System.out.print("Escolha uma opção: ");
            int userOption = scanner.nextInt();

            if (userOption <= 0 || userOption > currencyMenuLength) {
                System.out.println("Opção Inválida! Escolha uma opção válida!");
                continue;
            }

            CurrenciesMenuOptionsEnum currenciesMenuOptionsEnum = CurrenciesMenuOptionsEnum.values()[userOption - 1];

            if(currenciesMenuOptionsEnum == CurrenciesMenuOptionsEnum.EXIT) {
                break;
            }

            System.out.print("Digite o valor que deseja converter: ");
            double value = scanner.nextDouble();

            String fromSymbol = currenciesMenuOptionsEnum.getFromCurrencySymbol();
            String toSymbol = currenciesMenuOptionsEnum.getToCurrencySymbol();

            double convertedCurrencyPrice = new App().getCalculatedExchangePrice(value, fromSymbol, toSymbol);

            System.out.printf("\nValor %.2f [%s] corresponde ao valor final de %.2f [%s]\n\n", value, fromSymbol, convertedCurrencyPrice, toSymbol);
            System.out.println("·····················································································");
        }
    }
}
